name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Download autorel
        run: |
          wget https://github.com/jcornaz/autorel/releases/download/v0.1.5/autorel
          chmod +x autorel

      - name: Release
        run: ./autorel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
